name: Condition Demo

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Provide the environment name (e.g., Development, Test, Production)'
        required: true
        default: 'Development'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'Production'

    steps:
      - name: Step 1
        run: echo "Hello"

      - name: step 2
        if: failure()
        run: echo "Runs only if Step 1 failed"