name: Env Variables demo

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Use environment variables
        env:
          Print_API_URL: ${{ vars.API_URL }}
          Print_API_KEY: ${{ secrets.API_KEY }}
        run: |          
          echo "API URL: $Print_API_URL"
          echo "API Key: $Print_API_KEY"
