name: Env Variables demo

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Use environment variables
        env:
          API_URL: ${{ vars.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |          
          echo "API URL: $API_URL"
          echo "API Key: $API_KEY"
