name: Env Variables demo

on: workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Use environment variables
        env:
          Print_API_URL: $API_URL
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Outputs the API URL environment variable to the workflow logs
          # This step echoes the API_URL for debugging and verification purposes
          echo "API URL: $API_URL"
          echo "API Key: $API_KEY"
